### ISSUE TITLE
Link to Page that has the image Name

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki-plugin-gallery#10]
I am currently using the great gallery plugin together with the brand new dokutouch theme. 
Because of this, I have all my images named after my pages (so they display nicely in the left dokutouch column). 
It would be nice, if the gallery plugin could link to these pages. 
For images that do not have a page equivalent (e.g. the dokuwiki-128.png) there could be no link. (or the direct link as a fallback)
Implemented as a new parameter ("page" instead of "direct" or so) this could be highly usable!!

I experimented a little bit:

Adding

```
 }elseif($data['page']) {
            $new_id = cleanID($data['ns'].':'.substr($a['title'], 0, -strlen(strrchr($a['title'], '.'))));
            $newpath = wikiFN($new_id);
            if ( @file_exists($newpath) ) {
              $href = "/doku.php/".$data['ns']."/".substr($a['title'], 0, -strlen(strrchr($a['title'], '.')));
            }else{
              $href   = ml($img['id'],array('id'=>$ID),$data['direct']);
            } 
```

In line 534 of syntax.php and adding "page" in metadata.php and setting $data['page'] = false (Around line 84) gives the result I wanted. This is of course not yet foolproof. But very nice already.

The code below acts even more sophisticated: if multiple images with different numbers at the end exist, all images link to the page. E.g.:
Page: Cake
Images: cake, cake2, cake3. The Numbers get cut off, all images link to the "Cake" page.

```
        }elseif($data['page']) {
            $sitename = substr($a['title'], 0, -strlen(strrchr($a['title'], '.')));
            $new_id = cleanID($data['ns'].':'.$sitename);
            $newpath = wikiFN($new_id);
            if ( @file_exists($newpath) ) {
              $href = "/doku.php/".$data['ns']."/".$sitename;
            }else{
              while (is_numeric(substr($sitename, -1))) {  //Remove all trailing numbers.
                $sitename = substr($sitename, 0, -1);  
              }
              $new_id = cleanID($data['ns'].':'.$sitename);
              $newpath = wikiFN($new_id);
              if ( @file_exists($newpath) ) {
                $href = "/doku.php/".$data['ns']."/".$sitename; 
              }else {
                $href   = ml($img['id'],array('id'=>$ID),$data['direct']);
              }
            }
```

**Comment by oakbrad** [comment]
Hi, I was interested in doing this as well. Since you posted long ago, wondering if you have tested this code with "Frusterick Manners" or implemented any improvements since. Thanks!

**Comment by splitbrain** [comment]
this was copied from a page comment a long time ago. I'm not sure I understand what the goal is here. closing this. if someone knows what it means, a new issue can always be opened.
