### ISSUE TITLE
Use CSS max-width and max-height instead of attributes on images

### ISSUE THREAD

**Issue by BilliAlpha** [splitbrain/dokuwiki-plugin-gallery#103]
I think it would make more sense to use CSS to define the size of the picture instead of html attributes.
Example : 
```HTML
<img src="picture.jpg" style="max-width: 120px; max-height: 120px;"/>
```
Instead of
```HTML
<img src="picture.jpg" width="120" height="120" border="0"/>
```

I might create a pull request for this in the near future.

**Comment by mprins** [comment]
removing width and/or height may cause page reflows

**Comment by BilliAlpha** [comment]
In this case how should I do to keep the aspect ratio without knowing the size of the picture ?
