### ISSUE TITLE
Default crop not working on some pages

### ISSUE THREAD

**Issue by wedge47** [splitbrain/dokuwiki-plugin-gallery#118]
Dokuwiki: Release 2018-04-22a "Greebo"
Gallery Plugin: latest (checked 2018-12-17)

I'm using dokuwiki and galleryplugin for some years now without issues. Issues occurs in an installation where I do a monthly picture voting in conjunction with rate and wrap plugin, just in case this is important.

Problem: 
- gallery default is set to: cache, crop and lightbox
![image](https://user-images.githubusercontent.com/45931845/50071679-e9df5b80-01d2-11e9-8c27-b289aeabefe9.png)
- images get cropped on old pages .. on new pages it is not working anymore
- even a single page with old an new images .. old ones get cropped new pictures not
- even with explicit mentioning of crop attribute in syntax images are not cropped

Tried to solve as follows
- uninstalled and reinstalled gallery plugin
- tried clearing cache
- looking for syntax errors but could not find any

**Comment by wedge47** [comment]
Hi, thanks for quick response .. i checked phpinfo() ..seams that gd is enabled
![image](https://user-images.githubusercontent.com/45931845/50074131-35960300-01db-11e9-8678-ca5cfaa53bd9.png)

**Comment by wedge47** [comment]
want to bring this up again as i did not find a solution until now. Any more ideas? Do you need more data?

**Comment by splitbrain** [comment]
do you have the im_convert option set?

**Comment by wedge47** [comment]
I would say now. Should be default setting

![image](https://user-images.githubusercontent.com/45931845/51531512-ed9f7700-1e3d-11e9-8e41-583d85532cac.png)

**Comment by splitbrain** [comment]
hmm. no idea. what size are your original images? what's your memory limit?

**Comment by wedge47** [comment]
original images are 1920x1080 ... memorylimit is -1

**Comment by splitbrain** [comment]
the memory limit is the problem. current stable fails to parse -1. set a sensible limit instead and it should work again.

**Comment by wedge47** [comment]
added ini_set('memory_limit','128M'); to doku.php  and php_value memory_limit 128M to .htaccess file with no luck. I'm not allowed to edit php.ini

you say current stable..so this is an issue that will be fixed in one of the next releases?

**Comment by Michaelsy** [comment]
You can try to switch to PHP 5.6 or 7.1

Or apply this patch: https://github.com/splitbrain/dokuwiki/pull/2420/files
(Be aware this method is not update-safe.)

In your tests you should purge the DokuWiki cache by deleting the entire contents of the dir /data/cache

Feedback welcome - Michael Sy.

**Comment by wedge47** [comment]
Michael thank you! .. this little patch did the trick. No need to clear the cache or anything. Hope this fix finds it's way into one of the next stable versions.

greetings wedge
