### ISSUE TITLE
Some photos break the gallery

### ISSUE THREAD

**Issue by samuelpenn** [splitbrain/dokuwiki-plugin-gallery#136]
I've noticed that some of my photos cause the gallery to break. I get a white page when I try to browse to the page that has a gallery that includes the photo. Also the full page media manage isn't able to show details on that photo.

However, if I directly include the photo on a page, it displays fine.

I'm using latest stable Dokuwiki and Gallery plugin, on Ubuntu 18.04. I get the following error in the Apache logs when viewing the page:

[Sat Sep 21 16:44:38.028668 2019] [php7:error] [pid 12673] [client 82.68.244.238:53272] PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in /data/www/www.notasnark.com/inc/JpegMeta.php:1557\nStack trace:\n#0 /data/www/www.notasnark.com/inc/JpegMeta.php(1103): JpegMeta->_parseMarkerXmp()\n#1 /data/www/www.notasnark.com/inc/JpegMeta.php(622): JpegMeta->_parseAll()\n#2 /data/www/www.notasnark.com/inc/JpegMeta.php(230): JpegMeta->getDates()\n#3 /data/www/www.notasnark.com/inc/JpegMeta.php(155): JpegMeta->getDateField('EarliestTime')\n#4 /data/www/www.notasnark.com/inc/media.php(1107): JpegMeta->getField(Array)\n#5 /data/www/www.notasnark.com/inc/media.php(1136): media_getTag(Array, Object(JpegMeta))\n#6 /data/www/www.notasnark.com/inc/media.php(1157): media_file_tags(Object(JpegMeta))\n#7 /data/www/www.notasnark.com/inc/media.php(926): media_details('photos:2012:tan...', 255, false, Object(JpegMeta))\n#8 /data/www/www.notasnark.com/inc/template.php(1465): media_tab_view('photos:2012:tan...', 'photos:2012', 255, false)\n#9 /data/www/www.notasnark.com/inc/Ajax.php(240): tpl_mediaFileDetails('photos in /data/www/www.notasnark.com/inc/JpegMeta.php on line 1557, referer: https://www.notasnark.net/index?do=media&ns=

I can't see what the difference is between the 'broken' photos and the working ones. Many have been taken with the same camera, edited in the same software and previously stored in Google Photos.

An example image which causes problems is this one:
https://www.notasnark.net/_media/photos/tankfest-1.jpg?w=400&tok=42de43

**Comment by splitbrain** [comment]
This is not a problem in the Gallery plugin. This happens when parsing EXIF data in DokuWiki core. Your installation is missing the XML extension.
