### ISSUE TITLE
Bug ? missing function xml_parser_create()

### ISSUE THREAD

**Issue by uxiyon** [splitbrain/dokuwiki-plugin-gallery#139]
Hi,

I have an error when trying to have a gallery from this content :
{{gallery>:photos:mesanges:abri}}

where photos:mesanges:abri are directories created by hand, and set the rights to apache:apache (CentOS 7)

The error message is :
[Sun Jan 12 21:10:36.109152 2020] [php7:error] [pid 24487] [client 192.168.20.1:37864] PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in /opt/wiki/inc/JpegMeta.php:1557\nStack trace:\n#0 /opt/wiki/inc/JpegMeta.php(330): JpegMeta->_parseMarkerXmp()\n#1 /opt/wiki/inc/JpegMeta.php(151): JpegMeta->getXmpField('dc:title')\n#2 /opt/wiki/inc/JpegMeta.php(597): JpegMeta->getField(Array)\n#3 /opt/wiki/inc/JpegMeta.php(161): JpegMeta->getTitle()\n#4 /opt/wiki/lib/plugins/gallery/syntax.php(612): JpegMeta->getField(Array)\n#5 /opt/wiki/lib/plugins/gallery/syntax.php(521): syntax_plugin_gallery->_meta(Array, 'title')\n#6 /opt/wiki/lib/plugins/gallery/syntax.php(400): syntax_plugin_gallery->_image(Array, Array)\n#7 /opt/wiki/lib/plugins/gallery/syntax.php(151): syntax_plugin_gallery->_gallery(Array)\n#8 /opt/wiki/inc/parser/renderer.php(111): syntax_plugin_gallery->render('xhtml', Object(Doku_Renderer_xhtml), Array)\n#9 /opt/wiki/inc/parserutils.php(654): Doku_Renderer->plugin('gallery', Array, 5, '{{gallery>:phot...')\n#10 /opt/wiki/inc/parserutils.php(130): p_render('xhtml', Array, NULL)\n#11 /opt/wiki in /opt/wiki/inc/JpegMeta.php on line 1557

**Comment by ryannathans** [comment]
hmm I am having the same issue, seems like some specific image metadata is causing it

**Comment by ryannathans** [comment]
[priest_in_peril.zip](https://github.com/splitbrain/dokuwiki-plugin-gallery/files/9330600/priest_in_peril.zip)
should be able to repro the issue with this image

**Comment by splitbrain** [comment]
The exif parser requires the xml extension to be installed.
