### ISSUE TITLE
gallery_center flex model css

### ISSUE THREAD

**Issue by vaniwiki** [splitbrain/dokuwiki-plugin-gallery#140]
```
div.dokuwiki div.gallery_center {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    width: 100%;
}
```

**Comment by molefunk** [comment]
Oh, I had forgot. I have set the default number of images per line to 0 in config, so it doesn't output a table, but div's. I suppose that might affect the outcome of this solution, but it works. Flex-model for the win! :)

**Comment by Floffyko** [comment]
Do you mean line 45 from screen.less?
