### ISSUE TITLE
showname with long filenames breaks the layout

### ISSUE THREAD

**Issue by gabuzom** [splitbrain/dokuwiki-plugin-gallery#144]
Steps to reproduce: 

* upload one or more image(s) with one improbably long filename (and no spaces)
* display them in a gallery

=> the column(s) where these longname images appear would be as wide as the long filename written without a linebreak

Suggested solutions: 
* fix a max-filename-length variable, and after that length either:
  * display "..." and the rest of the filename on hover (or not)
  * display the name over sveral lines (would slightly break the layout of the current line in height, but seems totally acceptable.

Overall and besides this minor annyance, thanks zillions for the Gallery plugin, that truly rocks!! <3

**Comment by gabuzom** [comment]
After further tests it appears that this problem arises with filenames that 
* contain only alpha-numeric characters
* contain only alpha-numeric characters and underscores
but not that
* contain hyphens
as long hyphen-containing filenames are indeed being broken in several lines!

suggested fix would be: treat underscores like hyphens + set a max-length for non-hyphenated non-underscored long filnenames, after which a) they get "..." instead of the end of the filename b) they are put on several lines after every max-length characters....

**Comment by mprins** [comment]
If you can provide a PR that does this using CSS (`text-overflow: ellipsis;`)
see https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow
