### ISSUE TITLE
Feature request: whole gallery linking 

### ISSUE THREAD

**Issue by gabuzom** [splitbrain/dokuwiki-plugin-gallery#146]
Hello! I appreciate a lot Gallery and how flexible it is!! <3 Recently friends and i started using small gallery strips of random images as separators on pages... this looks great!! 

Yet, for the first time i realized that the options for *linking* within the gallery are pretty limited. There is mostly "direct", but that's all.. I think it would be nice (and relatively easy to implement) to have options to:
* have no link at all on the whole gallery. It is one block, non-clickable.
* have ONE link for the whole gallery. Whichever image you click and you get to that link (...&link:https://blah...)

Or do you think it would be superfluous/non-trivial to implement?

Cheers and thanks a lot for great plugin \o/

**Comment by splitbrain** [comment]
not planned
