### ISSUE TITLE
Prosemirror integration is broken

### ISSUE THREAD

**Issue by annda** [splitbrain/dokuwiki-plugin-gallery#169]
After recent refactoring, the plugin no longer works with prosemirror installed. More specifically, the wiki stops working:

```
2023-08-31 09:37:38	/www/dokuwiki/lib/plugins/gallery/action/prosemirror.php(44)	Error: Call to a member function getDataFromParams() on null
  #0 /www/dokuwiki/inc/Extension/EventHandler.php(80): action_plugin_gallery_prosemirror->writeDefaultsToJSINFO()
  #1 /www/dokuwiki/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
  #2 /www/dokuwiki/inc/Extension/Event.php(132): dokuwiki\Extension\Event->advise_before()
  #3 /www/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
  #4 /www/dokuwiki/doku.php(120): dokuwiki\Extension\Event::createAndTrigger()
  #5 {main}
```

**Comment by gittlelit** [comment]
Similar for me after upgrading to latest stable docuwiki then updating gallery plugin. Using Bootstrap3 theme.
<code>
2023-08-31 09:37:38	/www/dokuwiki/lib/plugins/gallery/action/prosemirror.php(44)	Error: Call to a member function getDataFromParams() on null
  #0 /www/dokuwiki/inc/Extension/EventHandler.php(80): action_plugin_gallery_prosemirror->writeDefaultsToJSINFO()
  #1 /www/dokuwiki/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
  #2 /www/dokuwiki/inc/Extension/Event.php(132): dokuwiki\Extension\Event->advise_before()
  #3 /www/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
  #4 /www/dokuwiki/doku.php(120): dokuwiki\Extension\Event::createAndTrigger()
  #5 {main}
</code>

Then after removing prosemirror things appeared to work but when trying to access the admin section to configure things:
<code>
  2023-08-31 17:01:52     /var/www/html/web.domain.domain/public_html/lib/plugins/gallery/classes/Options.php(20) ParseError: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
  #0 [internal function]: load_autoload('dokuwiki/plugin...')
  #1 /var/www/html/web.domain.domain/public_html/lib/plugins/gallery/conf/metadata.php(19): spl_autoload_call('dokuwiki\\plugin...')
  #2 /var/www/html/web.domain.domain/public_html/lib/plugins/config/core/Loader.php(201): include('/var/www/html/c...')
  #3 /var/www/html/web.domain.domain/public_html/lib/plugins/config/core/Loader.php(53): dokuwiki\plugin\config\core\Loader->loadExtensionMeta('/var/www/html/c...', 'plugin', 'gallery')
  #4 /var/www/html/web.domain.domain/public_html/lib/plugins/config/core/Configuration.php(51): dokuwiki\plugin\config\core\Loader->loadMeta()
  #5 /var/www/html/web.domain.domain/public_html/lib/plugins/config/admin.php(40): dokuwiki\plugin\config\core\Configuration->__construct()
  #6 /var/www/html/web.domain.domain/public_html/inc/Action/Admin.php(33): admin_plugin_config->handle()
  #7 /var/www/html/web.domain.domain/public_html/inc/ActionRouter.php(83): dokuwiki\Action\Admin->preProcess()
  #8 /var/www/html/web.domain.domain/public_html/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction('admin')
  #9 /var/www/html/web.domain.domain/public_html/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct()
  #10 /var/www/html/web.domain.domain/public_html/inc/actions.php(16): dokuwiki\ActionRouter::getInstance(true)
  #11 /var/www/html/web.domain.domain/public_html/doku.php(126): act_dispatch()
  #12 {main}
2023-08-31 17:01:52     /var/www/html/web.domain.domain/public_html/lib/plugins/gallery/conf/metadata.php(19)   Error: Class 'dokuwiki\plugin\gallery\classes\Options' not found
  #0 /var/www/html/web.domain.domain/public_html/lib/plugins/config/core/Loader.php(201): include()
  #1 /var/www/html/web.domain.domain/public_html/lib/plugins/config/core/Loader.php(53): dokuwiki\plugin\config\core\Loader->loadExtensionMeta('/var/www/html/c...', 'plugin', 'gallery')
  #2 /var/www/html/web.domain.domain/public_html/lib/plugins/config/core/Configuration.php(51): dokuwiki\plugin\config\core\Loader->loadMeta()
  #3 /var/www/html/web.domain.domain/public_html/lib/plugins/config/admin.php(40): dokuwiki\plugin\config\core\Configuration->__construct()
  #4 /var/www/html/web.domain.domain/public_html/inc/Action/Admin.php(33): admin_plugin_config->handle()
  #5 /var/www/html/web.domain.domain/public_html/inc/ActionRouter.php(83): dokuwiki\Action\Admin->preProcess()
  #6 /var/www/html/web.domain.domain/public_html/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction('admin')
  #7 /var/www/html/web.domain.domain/public_html/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct()
  #8 /var/www/html/web.domain.domain/public_html/inc/actions.php(16): dokuwiki\ActionRouter::getInstance(true)
  #9 /var/www/html/web.domain.domain/public_html/doku.php(126): act_dispatch()
  #10 {main}
</code>

**Comment by MartijnRas** [comment]
I worked around this rather crudely, by guarding $syntax: 

public function writeDefaultsToJSINFO(Doku_Event $event, $param)
    {   
        global $JSINFO;

        /** @var syntax_plugin_gallery $syntax */
        $syntax = plugin_load('syntax', 'gallery');
        if ($syntax) {
                $defaults = $syntax->getDataFromParams($syntax->getConf('options'));
                $attributes = $this->cleanAttributes($defaults);

                if (!isset($JSINFO['plugins'])) {
                    $JSINFO['plugins'] = [];
                }
                $JSINFO['plugins']['gallery'] = [
                    'defaults' => array_map(function ($default) {
                        return ['default' => $default,];
                    }, $attributes),
                ];
                $JSINFO['plugins']['gallery']['defaults']['namespace'] = ['default' => ''];
            }
    }
