### ISSUE TITLE
Install of 'gallery' fails

### ISSUE THREAD

**Issue by sinkva** [splitbrain/dokuwiki-plugin-gallery#174]
Release 2023-04-04a "Jack Jackrum"
attempting to install using Extension Manager > Search Extension
--------------------------------------------------
results in:
Error: Class 'dokuwiki\plugin\gallery\classes\Options' not found
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the gallery plugin.
More info has been written to the DokuWiki error log.
--------------------------------------------------
error log says:
2023-09-09 20:52:37	/home/cscaggs/public_html/lib/plugins/gallery/syntax/main.php(52)	Error: Class 'dokuwiki\plugin\gallery\classes\Options' not found
  #0 /home/cscaggs/public_html/inc/parser/handler.php(284): syntax_plugin_gallery_main->handle(':2023-05-29_mem...', 5, 476, Object(Doku_Handler))
  #1 /home/cscaggs/public_html/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('{{gallery>:2023...', 5, 476, 'gallery_main')
  #2 /home/cscaggs/public_html/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('{{gallery>:2023...', 5, 476)
  #3 /home/cscaggs/public_html/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '{{gallery>:2023...', '_plugin_gallery...', 476, 476)
  #4 /home/cscaggs/public_html/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('\n')
  #5 /home/cscaggs/public_html/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse('\n====== Memoria...')
  #6 /home/cscaggs/public_html/inc/parserutils.php(198): p_get_instructions('====== Memorial...')
  #7 /home/cscaggs/public_html/lib/plugins/include/helper.php(269): p_cached_instructions('/home/cscaggs/p...', false, 'blog:2023-05-29...')
  #8 /home/cscaggs/public_html/lib/plugins/include/syntax/include.php(150): helper_plugin_include->_get_instructions('blog:2023-05-29...', NULL, 'page', 0, Array, 'start', Array)
  #9 /home/cscaggs/public_html/inc/parser/renderer.php(119): syntax_plugin_include_include->render('metadata', Object(Doku_Renderer_metadata), Array)
  #10 /home/cscaggs/public_html/inc/parserutils.php(540): Doku_Renderer->plugin('include_include', Array, 5, '{{page>blog:202...')
  #11 /home/cscaggs/public_html/inc/parserutils.php(299): p_render_metadata('start', Array)
  #12 /home/cscaggs/public_html/inc/common.php(266): p_get_metadata('start')
  #13 /home/cscaggs/public_html/doku.php(97): pageinfo()
  #14 {main}

**Comment by splitbrain** [comment]
fixed with 7d44814ddb26da622bf4bcbbdaf537be26a3339a
