### ISSUE TITLE
Call to undefined function sexplode() after update of gallery

### ISSUE THREAD

**Issue by lchabin** [splitbrain/dokuwiki-plugin-gallery#175]
update from 2021-09-11 to 2023-09-03 on a Release 2022-07-31a "Igor" -> dirty plugin crash

2023-09-10 12:32:46	/home/wiki/lib/plugins/gallery/syntax/main.php(62)	Error: Call to undefined function sexplode()
  #0 /home/wiki/inc/parser/handler.php(279): syntax_plugin_gallery_main->handle(':dessins_rre:en...', 5, 29, Object(Doku_Handler))
  #1 /home/wiki/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('{{gallery>:dess...', 5, 29, 'gallery_main')
  #2 /home/wiki/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('{{gallery>:dess...', 5, 29)
  #3 /home/wiki/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '{{gallery>:dess...', '_plugin_gallery...', 29, 29)
  #4 /home/wiki/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('\n\n====== Conf\xC3\xA9...')
  #5 /home/wiki/inc/parserutils.php(223): dokuwiki\Parsing\Parser->parse('\n\n====== Enleve...')
  #6 /home/wiki/inc/parserutils.php(188): p_get_instructions('\n====== Enlevem...')
  #7 /home/wiki/inc/parserutils.php(510): p_cached_instructions('/home/sceadsuarcu...', false, 'dessins_raoul_r...')
  #8 /home/wiki/inc/parserutils.php(289): p_render_metadata('dessins_raoul_r...', Array)
  #9 /home/wiki/inc/common.php(246): p_get_metadata('dessins_raoul_r...')
  #10 /home/wiki/doku.php(97): pageinfo()
  #11 {main}

**Comment by splitbrain** [comment]
your wiki is outdated

**Comment by lchabin** [comment]
The gallery plugin is marked as compatible with 2022-07-31 "Igor". 
Shouldn't it be marked as Not compatible then ?
That's why I have upgraded the plugin. Shouldn't have.
