### ISSUE TITLE
"An unforeseen error has occured" after update

### ISSUE THREAD

**Issue by bellingeri** [splitbrain/dokuwiki-plugin-gallery#180]
Hi.

We updated the plugin today and every page with the {{gallery>.:}} tag reports this data:

>Error: Class 'dokuwiki\plugin\gallery\classes\BasicFormatter' not found
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the gallery plugin.
More info has been written to the DokuWiki error log.

In the log we have these lines:

> 2023-09-14 13:38:11Error: Class 'dokuwiki\plugin\gallery\classes\BasicFormatter' not found/var/www/vhosts/[...]/httpdocs/wiki/lib/plugins/gallery/syntax/main.php(97)
    #0 /var/www/vhosts/[...]/httpdocs/wiki/inc/parser/renderer.php(119): syntax_plugin_gallery_main->render('metadata', Object(Doku_Renderer_metadata), Array)
    #1 /var/www/vhosts/[...]/httpdocs/wiki/inc/parserutils.php(540): Doku_Renderer->plugin('gallery_main', Array, 5, '{{gallery>.:}}')
    #2 /var/www/vhosts/[...]/httpdocs/wiki/inc/parserutils.php(299): p_render_metadata('clienti:alba:st...', Array)
    #3 /var/www/vhosts/[...]/httpdocs/wiki/inc/common.php(266): p_get_metadata('clienti:alba:st...')
    #4 /var/www/vhosts/[...]/httpdocs/wiki/doku.php(97): pageinfo()
    #5 {main}

Thanks for the help.

**Comment by splitbrain** [comment]
which dokuwiki and php versions are you running?

**Comment by bellingeri** [comment]
The original PHP version (which has the problem) was 7.3.33.
Updated to 7.4.33 the problem seems solved.
DokuWiki version: 2023-04-04a "Jack Jackrum".

Thank you.
