### ISSUE TITLE
Title and caption separator character

### ISSUE THREAD

**Issue by KodeIn** [splitbrain/dokuwiki-plugin-gallery#183]
Hi,

I find it problematic to use the '-' character as a separator between title and caption since it's a frequently used character.
For example, it's frequently used in devices s/n and parts references so if I want to title an image with a part number it'll be cut between title and caption.
In French we also have quite a few frequently used composed words that use '-' in them (like "après-midi" that translate to "afternoon").

Maybe it would be better to use another "rarer" character altogether like '|' which is already frequently used by dokuwiki as a separator. 

I think something like this would be quite OK :
```
<gallery options_goes_here>
:myfolder:myimage.jpg Title of the image that could contain - in it without trouble|Caption of the image
</gallery>
```

**Comment by Laynee** [comment]
Yes please change the `-` separator to something like `|`. Using a dash as separator would lead to multiple problems : 

- for music albums : James Brown - Live at the Apollo (1963)
- for books : Philip K. Dick - Ubik (1969)
