### ISSUE TITLE
Norecursive option doesn't work

### ISSUE THREAD

**Issue by ghost** [splitbrain/dokuwiki-plugin-gallery#19]
I want to disable the "recursive" option for a specific page.  Appending "?norecursive" to the namespace doesn't work (all images in subdirectories are also shown).

An example is my page here, which used to show only two images but since updating dokuwiki now shows all images from subdirectories also:
  http://www.sokoll.net/doku.php/pastimes:rc:mpx:spektrum

**Comment by splitbrain** [comment]
should be fixed
