### ISSUE TITLE
Vertical crop doesn't work with external images

### ISSUE THREAD

**Issue by adamshand** [splitbrain/dokuwiki-plugin-gallery#36]
When I use the crop parameter with local images it works as expected:

```
{{gallery>:?0&96x160&crop}}
```

However if I use it with external images the horizontal parameter behaves as expected, but the vertical parameter appears to be ignored.  

```
{{gallery>http://www.23hq.com/rss/schabloni?0&96x160&crop}}
```

I'm using Weatherwax and the Gallery 2013-02-16.

**Comment by splitbrain** [comment]
Be sure your fetchsize is large enough to download the images.
