### ISSUE TITLE
Sizing with direct parameter doesn't work

### ISSUE THREAD

**Issue by adamshand** [splitbrain/dokuwiki-plugin-gallery#37]
Setting a sized bounding box for the direct parameter seems to be ignored.  The command I'm using is:

```
{{gallery>:?0&96x160&64X64&crop&direct}}
```

I do get linked directly to the image but the size doesn't seem to be honoured at all.

I'm using Weatherwax and Gallery 2013-02-16.

**Comment by splitbrain** [comment]
Obsolete. X sizing now only affects the lightbox, not the direct link anymore.
