### ISSUE TITLE
warning Missing argument 1 for SimplePie_File::SimplePie_File(),

### ISSUE THREAD

**Issue by herrmannj** [splitbrain/dokuwiki-plugin-gallery#4]
Hi,

I' get this error if I use picassa (feed)  as source

Warning: Missing argument 1 for SimplePie_File::SimplePie_File(), called in /homepages.../www/inc/FeedParser.php on line 52 and defined in /homepages/.../www/inc/SimplePie.php on line 7650

Warning: file_get_contents() [function.file-get-contents]: Filename cannot be empty in /homepages/.../www/inc/SimplePie.php on line 7858

Important. the page has to be uncached ( or use ..?purge=true)

code

{{gallery>https://picasaweb.google.com/data/feed/base/user/...xxx.../albumid/...xxx...}}

**Comment by splitbrain** [comment]
can't reproduce with a real test url. probably fixed meanwhile
