### ISSUE TITLE
Feature wish: responsive design

### ISSUE THREAD

**Issue by eilko** [splitbrain/dokuwiki-plugin-gallery#58]
Dokuwiki becomes better and better on mobile devices. Your changes for audio and video in the latest release and earlier the vshare changes made our site more compatible with mobile devices. Two plugins we use are still not mobile aware. One of them is the gallery plugin. We wish it would become responsive towards smaller screens. Resize the images and keep the amount of columns or change the amount of columns based on screensize. Both options are fine with us.

**Comment by wishbone1138** [comment]
I'm also struggling with this.  I noticed if you reduce the number of images per row to 0, then it will work as you describe.  However, this also causes some strange behavior if the thumbnails are not all exactly the same size.  Some of them will float in the middle of the page after a smaller image.  I'm sure there's some css trickery I could use to potentially solve this,but I haven't figure it out yet.

**Comment by splitbrain** [comment]
You can use the crop parameter to make all thumbs the same size.

I'm happy about pull requests though.

**Comment by wishbone1138** [comment]
I tried that and if wasn't working as I though it would.   I tired a 80x80&crop.  It would make them smaller but still different sizes. crop didn't seem to do anything.  I'll mess with it some more today.

**Comment by wishbone1138** [comment]
I got it to work.  If you want to have a more responsive design you must make sure the following are configured:

Path to ImageMagick's convert tool - this must be set!  (eg, /usr/bin/convert)  I didn't have it set orginally.
Images per row - this must be set to zero
Gallery defaults - you'll want to turn on "crop"
Set your thumbnails to whatever size you want (I use 200x200 and it seems to work well for screen and mobile)

It won't resize the thumbnails dynamically (something more true to responsive), but it gets the job done for me.  I think I'd like to see an option that forces a widthxheight thumbnail requirement without cropping.  It would have to "pad" areas to make sure the image was the proper dimensions and still retain original aspect ratio.  Can't image magick do that?

**Comment by powerslave** [comment]
Here's another suggestion with minor css changes, which was enough for my responsive requirements.
The main change needed is to set a relative width on the div that's wrapping the thumb.

```css
div.gallery > div {
    width: 20%;
}
```
This scales the thumbnail container relative to the site width, and the image follows thanks to the inner `max-width:100%` on the img tag. The percent width controls the number of columns: 20% results in 5 columns, 25% in 4...

Gallery settings are 
* Images per row: 0
* Crop `checked`
* Square images 200x200

(I have not tested this with non-cropped images, or images with non-identical sizes)



------

you can see it in action on [bopx.ch](https://bopx.ch/pics/20170405-arosa_saisonabschluss/start)
In this case I have additional @media rules to control the number of columns depending on the page width, but that's optional.
```css
@media (max-width: 500px)
div.gallery>div {
    width: 33.3%;
}
```

![responsive_gallery](https://user-images.githubusercontent.com/853599/30671489-8009cca6-9e67-11e7-9a56-363d5d4e0e5c.gif)
