### ISSUE TITLE
feature request: allow more than one image argument

### ISSUE THREAD

**Issue by KaiMartin** [splitbrain/dokuwiki-plugin-gallery#69]
Currently, there is no way to show two or more specific images that do not match a simple pattern. 
Suggestion: 
Allow additional image arguments:
    {{gallery>foobar.png?foobaz.png?goo*.jpg}}

---<)kaimartin(>---
(Thank you for this very useful plugin)

**Comment by splitbrain** [comment]
just create a namespace and place your files in there. won't implement,

**Comment by KaiMartin** [comment]
> just create a namespace and place your files in there. won't implement,

namespaces don't solve my use case. 
will consider a fork.
---<)kaimartin(>---
