### ISSUE TITLE
Lightbox does not work well on mobile devices

### ISSUE THREAD

**Issue by modtronix-com** [splitbrain/dokuwiki-plugin-gallery#70]
Just started using this plugin short while ago. It is great!  The only thing is that the lightbox mode does not work well on mobile devices. Is there any upgrade? I looked at "lightbox2", and that works great on mobile devices. Does anyone know how hard it would be to replace prettyphoto with another lightbox script, like litebox2 for example? It is located here:
http://lokeshdhakar.com/projects/lightbox2/

**Comment by splitbrain** [comment]
Are you using an up-to-date version of the plugin? It uses the prettyPhoto library which works just fine on mobile. What exactly is not working for you?

**Comment by modtronix-com** [comment]
Hello

Thanks for quick reply! I have the latest version of the pluging. I went 
to Dokuwiki plugin manager, and checked the plugin is up to data.

If you for example open this page in mobile browser:
http://wiki.modtronix.com/doku.php?id=products:programmers:pgm-nucleo

If you click on any image, it is very small. If you then click on 
fullscreen mode(small icon in popup image window), it enlarges the 
image. But, not very well. It is in a window, that is not in middle of 
screen. And, if you click on image to get next image, it makes whole 
popup small again. It just does not work well on mobile device. Very 
hard getting large version of image.

Regards, David

=========================================
Modtronix Engineering
Sydney, Australia
Tel: +61 (0)405 353466
Fax: +61 (0)2 82094824
Email: david05@modtronix.com
Web: www.modtronix.com
ABN: 48663118043
