### ISSUE TITLE
Image Title character-limit

### ISSUE THREAD

**Issue by danieldupriest** [splitbrain/dokuwiki-plugin-gallery#77]
I am not sure if this is related to a limitation of Dokuwiki's EXIF functionality or the gallery plugin itself, but my image's EXIF titles seem to cut off (with ellipses "...") randomly between 60-something and 100-something characters.

This can be seen under thumbnails using "showtitle":

http://hypersweet.com/photos/2013/2013-05-23_australia_-_great_barrier_reef/home

As well as on an individual photo's detail page:

http://hypersweet.com/_detail/photos/2013/2013-05-23_australia_-_great_barrier_reef/img_1707.jpg?id=photos%3A2013%3A2013-05-23_australia_-_great_barrier_reef%3Ahome

Is this limit hard-coded somewhere in the code? If so I would be very grateful if this could be made an adjustable option in the settings, or at the very least I'd like to know where this number is set so I could increase it to something allowing longer descriptions, like 512 characters or more.

**Comment by splitbrain** [comment]
The gallery plugin does no shortening. I don't think DokuWiki does either. Check what the exif tags really are in those images. I suspect it's some other software shortening it. There might be a limit for EXIF...
