### ISSUE TITLE
Pagination is broken in gallery 2016-01-24

### ISSUE THREAD

**Issue by Laynee** [splitbrain/dokuwiki-plugin-gallery#81]
Tested with a folder of 20 images, gallery in `<table>` mode (`plugin»gallery»cols = 5`). When pagination is activated there are huge bugs. Every images in the folder are displayed and some are left out of the `<table>`. When the pagination is set to 5 or 10 it works.

`{{gallery>:photos?~10}}` works
`{{gallery>:photos?~8}}` does not work

On the other hand, one paginated gallery in `<div>` mode (`plugin»gallery»cols = 0`) works fine. But when inserting 2 paginated galleries on a page, the thumbnails of the last one are hidden but not the pagination links. And when a pagination link is clicked, the thumbnails appear.

Can you fix this, it's frustrating !
Thank you.

---

DokuWiki version : 2015-08-10 Detritus
Gallery plugin version : 2016-01-24
Default dokuwiki template

**Comment by micgro42** [comment]
To be more precise: It has to be a multiple of the number of thumbnails per row. This is annoying indeed, I'll look into it.
