### ISSUE TITLE
renders site unusable after upgrade to Frusterick Manners

### ISSUE THREAD

**Issue by KaiMartin** [splitbrain/dokuwiki-plugin-gallery#92]
After an upgrade to Frusterick Manners my dokuwiki site seemed to be
broken in a weird way. The pages render like they should when loaded
from the address line of the browser. Unfortunately, a left-mouse-button
click anywhere on the page immediately blacks-out. The view is not
completely black, just very dark. The content of the page can still be
seen as a faint shadow. There is a medium sized white cross in the upper
right. A scroll bar on the right still works. I can zoom in with
CTRL+scroll_wheel. But left-mouse-clicks on links or buttons do not seem
to have any effect at all.

These problems affected all dokuwiki pages, including admin and login. 

On the developer mailing list Markus Hitter hinted, that swipebox may be 
the culprit. Apparently, the gallery plugin makes heavy use of this tool. 
After I moved the gallery plugin out of the way, my site became usable again. 

---<)kaimartin(>---

**Comment by KaiMartin** [comment]
Just in case it matters, here is one of the gallery commands my site uses:
{{gallery>:eigenbau:lehrmittel:bauteilstecker:bilder?lightbox&showname&4 }}
(The problems affected pages without a gallery command, too)

---<)kaimartin(>---

**Comment by cvantum** [comment]
Same here. Did a Update from Dokuwiki by Web-Updater. After successfull update all my pages are covered with a black overlay and a white "X"-Button on the top-right position. 

While pressing ESC-Button i can get the pages but it's not possible to do a update or some tasks. 

It seems that the problem starts with the "swipebox"-Function. I've moved the full gallery-folder out of the plugins and made a full page-reload. After this it seems to work.

**Comment by splitbrain** [comment]
Update the gallery plugin. It's also mentioned in the DokuWiki changelog.

**Comment by KaiMartin** [comment]
I can confirm: The updated gallery plugin does not induce the black-outs. So the problem was already fixed a few months back. And this bug report is sort of obsolete.

The mention in the release notes is a bit low key, though. Actually, I read the relase notes before upgrading and failed to appreciate the significance of this item. The way it is presented as an example for the generic advice to update plugins made me expect the old version would at most make the pages with galleries fail. As it stands, the old version breaks each and every page, including admin and login. IMHO, a separate item in the release notes would be adequate. E.g:
- Update the [[plugin:Gallery|gallery plugin]]. Versions before 2016-12-22 break all pages in Frusterick Manners. This includes the login and the admin pages.

**Comment by splitbrain** [comment]
it's a wiki. feel free to improve the changelog where needed.
