### ISSUE TITLE
Nothing was found 2

### ISSUE THREAD

**Issue by kaapyth0n** [splitbrain/dokuwiki-plugin-gallery#94]
Hello! I'm trying to put an instagram gallery on dokuwiki, got the RSS
http://fetchrss.com/rss/58d0010c8a93f8ac2a8b4567620111429.xml

It does contain image links, also {{rss>}} works, but gallery plugin says "Nothing was found"
What could be wrong here?

**Comment by splitbrain** [comment]
see #90 only media feeds are supported. that feed only has html with images
