### ISSUE TITLE
Bug?: Cannot purge cache of gallery thumbnail images

### ISSUE THREAD

**Issue by powerslave** [splitbrain/dokuwiki-plugin-gallery#99]
My page has `{{gallery>:img.jpg}}`. I replaced `data/media/img.jpg` with a different image on disk (not through web upload).
I can't get the small gallery thumbnail image to show the new image. It seems to always read the old one from cache. The big lightbox popup image _does_ show the updated image.

I tried the following to purge the cache:

1. `?purge=true` on the page url containing the `{{gallery}}`
1. adding `&nocache` to the gallery call: `{{gallery>:img.jpg?nocache}}`
1. disabling cache in gallery by unchecking _cache_ in the admin gallery settings
1. adding `~~~NOCACHE~~~` to the page
1. adding `purge=true` to the actual small image url (right-click show image) `HOST/_media/img.jpg?w=200&h=200&tok=1ede80&purge=true`

For all cases, I made sure the image is not coming from browser cache, by hard-refreshing page (plus having browser cache disabled).

I'm using `Release 2017-02-19e "Frusterick Manners"` and the latest version of the **Gallery** plugin

**Comment by splitbrain** [comment]
Resizing is done in core, so this is the wrong repo. Thumbnail caches should automatically update when the original file is newer than the resized one. Since you did a copy on disk operation, you might have copied a file with an older modification timestamp.
